spring.application.name=msvc-medicos
# server.address=10.155.8.194
server.port=8081
spring.profiles.active=dev

springdoc.api-docs.enable=true
springdoc.swagger-ui.enable=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

