spring.application.name=msvc-medicos
server.port=8081
server.address=10.15.44.175
spring.profiles.active=dev

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html